/**
 * A sample week used by the empty state ("Try a sample week") so a new visitor can
 * see the planner working before adding anything of their own.
 * `day` is 0 = Monday ... 6 = Sunday.
 */
export type DemoEntry = {
  name: string;
  day: number;
  start: string; // "HH:MM"
  end: string; // "HH:MM"
  label: string;
  color: string; // tailwind-style class, e.g. "bg-cyan-500"
};

export const DEMO_WEEK: DemoEntry[] = [
  // Monday
  {
  name: "Morning Workout",
  day: 0,
  start: "07:00",
  end: "08:00",
  label: "fitness",
  color: "bg-cyan-500",
  },
  {
  name: "Breakfast",
  day: 0,
  start: "08:00",
  end: "08:30",
  label: "break",
  color: "bg-green-400",
  },
  {
  name: "Deep Work - Coding",
  day: 0,
  start: "09:00",
  end: "12:00",
  label: "work",
  color: "bg-red-500",
  },
  {
  name: "Lunch Break",
  day: 0,
  start: "12:00",
  end: "13:00",
  label: "break",
  color: "bg-green-400",
  },
  {
  name: "Meetings",
  day: 0,
  start: "14:00",
  end: "16:00",
  label: "admin",
  color: "bg-orange-500",
  },
  {
  name: "Email & Admin",
  day: 0,
  start: "16:00",
  end: "17:00",
  label: "admin",
  color: "bg-orange-500",
  },
  {
  name: "Dinner",
  day: 0,
  start: "18:00",
  end: "19:00",
  label: "break",
  color: "bg-green-400",
  },
  {
  name: "Evening Reading",
  day: 0,
  start: "20:00",
  end: "21:30",
  label: "relax",
  color: "bg-pink-400",
  },
  {
  name: "Wind Down",
  day: 0,
  start: "21:30",
  end: "23:00",
  label: "relax",
  color: "bg-pink-400",
  },
  // Tuesday
  {
  name: "Morning Workout",
  day: 1,
  start: "07:00",
  end: "08:00",
  label: "fitness",
  color: "bg-cyan-500",
  },
  {
  name: "Breakfast",
  day: 1,
  start: "08:00",
  end: "08:30",
  label: "break",
  color: "bg-green-400",
  },
  {
  name: "Study Session",
  day: 1,
  start: "09:00",
  end: "11:00",
  label: "study",
  color: "bg-purple-500",
  },
  {
  name: "Project Work",
  day: 1,
  start: "11:00",
  end: "13:00",
  label: "work",
  color: "bg-red-500",
  },
  {
  name: "Lunch",
  day: 1,
  start: "13:00",
  end: "14:00",
  label: "break",
  color: "bg-green-400",
  },
  {
  name: "Client Calls",
  day: 1,
  start: "15:00",
  end: "17:00",
  label: "admin",
  color: "bg-orange-500",
  },
  {
  name: "Creative Work",
  day: 1,
  start: "17:00",
  end: "18:30",
  label: "work",
  color: "bg-red-500",
  },
  {
  name: "Dinner",
  day: 1,
  start: "18:30",
  end: "19:30",
  label: "break",
  color: "bg-green-400",
  },
  {
  name: "Hobby Time",
  day: 1,
  start: "20:00",
  end: "22:00",
  label: "hobby",
  color: "bg-blue-400",
  },
  {
  name: "Relax",
  day: 1,
  start: "22:00",
  end: "23:00",
  label: "relax",
  color: "bg-pink-400",
  },
  // Wednesday
  {
  name: "Gym",
  day: 2,
  start: "07:00",
  end: "08:30",
  label: "fitness",
  color: "bg-cyan-500",
  },
  {
  name: "Breakfast",
  day: 2,
  start: "08:30",
  end: "09:00",
  label: "break",
  color: "bg-green-400",
  },
  {
  name: "Deep Focus",
  day: 2,
  start: "09:00",
  end: "12:00",
  label: "deep",
  color: "bg-fuchsia-500",
  },
  {
  name: "Lunch",
  day: 2,
  start: "12:00",
  end: "13:00",
  label: "break",
  color: "bg-green-400",
  },
  {
  name: "Team Sync",
  day: 2,
  start: "14:00",
  end: "15:00",
  label: "admin",
  color: "bg-orange-500",
  },
  {
  name: "Creative Work",
  day: 2,
  start: "15:00",
  end: "17:00",
  label: "work",
  color: "bg-red-500",
  },
  {
  name: "Planning",
  day: 2,
  start: "17:00",
  end: "18:00",
  label: "admin",
  color: "bg-orange-500",
  },
  {
  name: "Dinner",
  day: 2,
  start: "18:00",
  end: "19:00",
  label: "break",
  color: "bg-green-400",
  },
  {
  name: "Learning",
  day: 2,
  start: "19:30",
  end: "21:00",
  label: "study",
  color: "bg-purple-500",
  },
  {
  name: "TV Time",
  day: 2,
  start: "21:00",
  end: "23:00",
  label: "relax",
  color: "bg-pink-400",
  },
  // Thursday
  {
  name: "Morning Run",
  day: 3,
  start: "07:00",
  end: "08:00",
  label: "fitness",
  color: "bg-cyan-500",
  },
  {
  name: "Breakfast",
  day: 3,
  start: "08:00",
  end: "08:30",
  label: "break",
  color: "bg-green-400",
  },
  {
  name: "Learning Time",
  day: 3,
  start: "09:00",
  end: "11:00",
  label: "study",
  color: "bg-purple-500",
  },
  {
  name: "Development",
  day: 3,
  start: "11:00",
  end: "13:00",
  label: "work",
  color: "bg-red-500",
  },
  {
  name: "Lunch Break",
  day: 3,
  start: "13:00",
  end: "14:00",
  label: "break",
  color: "bg-green-400",
  },
  {
  name: "Planning",
  day: 3,
  start: "14:00",
  end: "16:00",
  label: "admin",
  color: "bg-orange-500",
  },
  {
  name: "Code Review",
  day: 3,
  start: "16:00",
  end: "17:30",
  label: "work",
  color: "bg-red-500",
  },
  {
  name: "Dinner",
  day: 3,
  start: "18:00",
  end: "19:00",
  label: "break",
  color: "bg-green-400",
  },
  {
  name: "Side Project",
  day: 3,
  start: "19:30",
  end: "21:30",
  label: "hobby",
  color: "bg-blue-400",
  },
  {
  name: "Chill Time",
  day: 3,
  start: "21:30",
  end: "23:00",
  label: "relax",
  color: "bg-pink-400",
  },
  // Friday
  {
  name: "Workout",
  day: 4,
  start: "07:00",
  end: "08:00",
  label: "fitness",
  color: "bg-cyan-500",
  },
  {
  name: "Breakfast",
  day: 4,
  start: "08:00",
  end: "08:30",
  label: "break",
  color: "bg-green-400",
  },
  {
  name: "Focus Block",
  day: 4,
  start: "09:00",
  end: "12:00",
  label: "deep",
  color: "bg-fuchsia-500",
  },
  {
  name: "Lunch",
  day: 4,
  start: "12:00",
  end: "13:00",
  label: "break",
  color: "bg-green-400",
  },
  {
  name: "Review & Wrap-up",
  day: 4,
  start: "14:00",
  end: "16:00",
  label: "admin",
  color: "bg-orange-500",
  },
  {
  name: "Team Happy Hour",
  day: 4,
  start: "17:00",
  end: "18:30",
  label: "social",
  color: "bg-violet-500",
  },
  {
  name: "Dinner",
  day: 4,
  start: "19:00",
  end: "20:00",
  label: "break",
  color: "bg-green-400",
  },
  {
  name: "Movie Night",
  day: 4,
  start: "20:30",
  end: "23:00",
  label: "relax",
  color: "bg-pink-400",
  },
  // Saturday
  {
  name: "Morning Yoga",
  day: 5,
  start: "08:00",
  end: "09:00",
  label: "fitness",
  color: "bg-cyan-500",
  },
  {
  name: "Brunch",
  day: 5,
  start: "10:00",
  end: "11:00",
  label: "break",
  color: "bg-green-400",
  },
  {
  name: "Personal Project",
  day: 5,
  start: "11:30",
  end: "14:00",
  label: "hobby",
  color: "bg-blue-400",
  },
  {
  name: "Lunch",
  day: 5,
  start: "14:00",
  end: "15:00",
  label: "break",
  color: "bg-green-400",
  },
  {
  name: "Errands",
  day: 5,
  start: "15:30",
  end: "17:00",
  label: "life",
  color: "bg-slate-500",
  },
  {
  name: "Dinner Prep",
  day: 5,
  start: "17:30",
  end: "18:30",
  label: "life",
  color: "bg-slate-500",
  },
  {
  name: "Dinner",
  day: 5,
  start: "18:30",
  end: "19:30",
  label: "break",
  color: "bg-green-400",
  },
  {
  name: "Social Time",
  day: 5,
  start: "20:00",
  end: "22:00",
  label: "social",
  color: "bg-violet-500",
  },
  {
  name: "Wind Down",
  day: 5,
  start: "22:00",
  end: "23:00",
  label: "relax",
  color: "bg-pink-400",
  },
  // Sunday
  {
  name: "Light Exercise",
  day: 6,
  start: "09:00",
  end: "10:00",
  label: "fitness",
  color: "bg-cyan-500",
  },
  {
  name: "Breakfast",
  day: 6,
  start: "10:00",
  end: "10:30",
  label: "break",
  color: "bg-green-400",
  },
  {
  name: "Reading",
  day: 6,
  start: "11:00",
  end: "13:00",
  label: "study",
  color: "bg-purple-500",
  },
  {
  name: "Lunch",
  day: 6,
  start: "13:00",
  end: "14:00",
  label: "break",
  color: "bg-green-400",
  },
  {
  name: "Meal Prep",
  day: 6,
  start: "14:30",
  end: "16:30",
  label: "life",
  color: "bg-slate-500",
  },
  {
  name: "Planning Week",
  day: 6,
  start: "17:00",
  end: "18:00",
  label: "admin",
  color: "bg-orange-500",
  },
  {
  name: "Dinner",
  day: 6,
  start: "18:30",
  end: "19:30",
  label: "break",
  color: "bg-green-400",
  },
  {
  name: "Family Time",
  day: 6,
  start: "20:00",
  end: "21:30",
  label: "social",
  color: "bg-violet-500",
  },
  {
  name: "Relax",
  day: 6,
  start: "21:30",
  end: "23:00",
  label: "relax",
  color: "bg-pink-400",
  },
  ];
